// server/seed-recognized-colleges.ts
import { db } from "./db";
import { colleges } from "@shared/schema";

async function seedRecognizedColleges() {
  const data = [
    // ----- Federal (Islamabad) Nursing Colleges -----
{
  name: "Fazaia College of Nursing & Allied Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["Generic BSN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Affiliated with Air University. Offers Generic BSN program recognized by PNMC.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "F.G. Polyclinic Hospital School of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["Generic BSN", "BSN Post RN", "Dip Midwifery"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Federal Government nursing institution offering BSN and Post RN programs with clinical practice at Polyclinic Hospital.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Foundation University Islamabad Campus (FUIC)",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["Generic BSN", "BSN Post RN", "Dip Midwifery", "Operation Theatre"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Recognized by PNMC and affiliated with Foundation University. Offers BSN and Post RN programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Health Services Academy",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["BSM"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Health Services Academy Islamabad offering Bachelor of Science in Midwifery program.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "PIMS College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["Generic BSN", "BSN Post RN", "MSN", "ICU", "CCU"],
  admissionFee: 35000,
  rating: null,
  reviewCount: 0,
  description: "Recognized by PNMC. Offers Generic BSN, Post RN, and MSN programs with clinical practice at PIMS Hospital.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "PIMS School of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["Generic BSN", "Dip Midwifery"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Part of Pakistan Institute of Medical Sciences, offering nursing diploma and BSN programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Regional Training Institute (RTI)",
  city: "Islamabad",
  province: "Federal",
  type: "government",
  programs: ["FWW"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Regional Training Institute offering Family Welfare Worker training programs under federal supervision.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Advanced Institute of Nursing and Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV", "CMW"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing institute offering BSN, Lady Health Visitor, and Community Midwifery programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Akhtar Saeed College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private institution providing Certified Nursing Assistant training.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Alhamd College of Nursing and Allied Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Affiliated with Alhamd Islamic University. Offers BSN and Lady Health Visitor programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Aman Medical Institute College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing college offering BSN and LHV programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Bashir Institute of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private college offering BSN and Post RN BSN programs recognized by PNMC.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "College of Nursing, National Institute of Modern Studies (NOVA)",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "CMW", "LHV"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "NOVA Institute offers nursing and midwifery programs with PNMC approval.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Dakson Institute of Management Sciences (IOMS) College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private college offering BSN, LHV, and CNA programs with modern facilities.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Department of Nursing, Iqra University Chak Shahzad Campus",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "CMW", "LHV", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Iqra University Nursing Department offering multiple nursing and allied health programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Fellow College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "Post RN BSN", "CNA", "LHV"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private institute offering multiple nursing training programs recognized by PNMC.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "HBS College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "CMW", "LHV", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "HBS Medical and Dental College’s nursing department offering BSN and diploma programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Health Aid College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private college offering BSN, LHV, and CNA programs under PNMC recognition.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Ibadat International University Islamabad",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "University offering BSN and Post RN BSN programs recognized by PNMC.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Islamabad Nursing College (Medical and Dental College Islamabad)",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing college offering undergraduate and Post RN nursing programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Islamabad Nursing College (Medical and Dental College Islamabad)",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing college offering undergraduate and Post RN nursing programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Isra College of Nursing Islamabad Campus",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["BSN Post RN", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Part of Isra University network offering Post RN BSN and CNA programs at Islamabad campus.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Khyber Pakhtoonkhwa Institute of Medical Sciences (IMS)",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing and medical sciences institute offering BSN and LHV programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Kulsum Institute of Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "Post RN BSN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private institute offering BSN and Post RN programs with modern learning facilities.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "National Excellence Institute of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "CMW", "LHV", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Recognized by PNMC, offering multiple nursing and allied programs including BSN, Post RN, and CMW.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "NCS Institute of Science, Quaid-e-Azam Campus",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV", "CMW"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "NCS Institute offering BSN and midwifery programs recognized by PNMC.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Midwest Institute of Sciences Islamabad (formerly NCS Institute of Sciences, Capital Campus)",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "LHV", "CNA"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Midwest Institute offering nursing, CNA, and LHV programs at its Islamabad campus.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Pak Institute of Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "LHV", "CNA", "CMW"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing college providing BSN, Post RN, LHV, and Midwifery programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Prime Institute of Nursing and Allied Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "Post RN BSN", "LHV", "CMW", "CNA", "ICU", "Peads"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Prime ION offers comprehensive nursing programs including BSN, Post RN, and specialized clinical training.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Professional College of Nursing and Allied Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "LHV", "CNA", "CMW"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Professional College of Nursing Islamabad offers a wide range of PNMC-recognized programs.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Radiant Institute of Health Sciences",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "Post RN BSN", "CNA", "LHV"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Private nursing college offering BSN and diploma programs with PNMC recognition.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Rawal Institute of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "ICU", "Peads"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Affiliated with Rawal Institute of Health Sciences, offering BSN and Post RN programs with advanced clinical training.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Sarhad University of Science and Information Technology (Islamabad Campus)",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN"],
  admissionFee: null,
  rating: null,
  reviewCount: 0,
  description: "Sarhad University Islamabad Campus offering BSN program recognized by PNMC.",
  contact: { phone: "", email: "", website: "" },
  accreditation: ["PNMC Approved"]
},
{
  name: "Shifa College of Nursing",
  city: "Islamabad",
  province: "Federal",
  type: "private",
  programs: ["Generic BSN", "BSN Post RN", "MSN", "PhD"],
  admissionFee: 40000,
  rating: 5,
  reviewCount: 250,
  description: "Part of Shifa Tameer-e-Millat University, offering BSN, Post RN, MSN, and PhD programs. Recognized for excellence in nursing education.",
  contact: { phone: "+92-51-846-4211", email: "info@stmu.edu.pk", website: "https://stmu.edu.pk" },
  accreditation: ["HEC Recognized", "PNMC Approved"]
}

  ];

  await db.insert(colleges).values(data);
  console.log("✅ Recognized nursing colleges seeded successfully");
}

seedRecognizedColleges()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seeding error:", err);
    process.exit(1);
  });
